# fly.toml app configuration file generated for mini-rag
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "mini-rag"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 8501
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

[env]
  API_BASE_URL = "http://localhost:8080"
